services:
  stats-server:
    build: stats-service/server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:16.1-alpine
    container_name: postgres-ewm-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1-alpine
    container_name: postgres-ewm-main-db
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ewm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stats-db-data:
  ewm-db-data:
