server:
  port: 9090

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always