CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255)                NOT NULL,
    uri       VARCHAR(2048)               NOT NULL,
    ip        VARCHAR(64)                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hits_timestamp ON hits (timestamp);
CREATE INDEX IF NOT EXISTS idx_hits_uri_timestamp ON hits (uri, timestamp);
CREATE INDEX IF NOT EXISTS idx_hits_uri_timestamp_ip ON hits (uri, timestamp, ip);
